version: '3.1'

services:

  mysql_1:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=libros
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - './volumenes/postgres:/var/lib/mysql'

  mysql_2:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=prestamos
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - './volumenes/postgres:/var/lib/mysql'

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - '27017:27017'
    volumes:
      - './volumenes/mongodb:/data/db'

  eureka-server:
    image: eureka-server
    build: ./eureka-server
    restart: always
    ports:
      - "8761:8761"

  clientes:
    image: cliente-service
    build: ./clientes
    restart: always
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
      - spring.data.mongodb.uri=mongodb://mongo:27017/clientes
    depends_on:
      - mongo
      - eureka-server

  libros:
    image: libro-service
    build: ./libros
    restart: always
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
      - spring.datasource.url=jdbc:mysql://mysql_1:3306/libros
      - spring.datasource.username=root
      - spring.datasource.password=admin
    depends_on:
      - eureka-server
      - mysql_1

  prestamos:
    image: prestamo-service
    build: ./prestamos
    restart: always
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
      - spring.datasource.url=jdbc:mysql://mysql_2:3306/prestamos
      - spring.datasource.username=root
      - spring.datasource.password=admin
    depends_on:
      - eureka-server
      - mysql_2

  gateway:
    image: gateway-service
    build: ./gateway
    ports:
      - "8080:8080"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - libros
      - clientes
      - prestamos